# Generated by Django 5.2.10 on 2026-03-22 19:32

import common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('requester', models.CharField(max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'low'), ('MED', 'medium'), ('HIGH', 'high')], default='MED', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('IN_PROGRESS', 'in_progress'), ('RESOLVED', 'resolved'), ('CLOSED', 'closed')], default='OPEN', max_length=15)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('issue_image', models.ImageField(blank=True, null=True, upload_to='issue_images/', validators=[common.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='facilities.facility')),
                ('tags', models.ManyToManyField(blank=True, related_name='issues', to='issues.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
