# Generated by Django 5.2.10 on 2026-02-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='requester',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
