# Generated by Django 5.2.10 on 2026-04-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_issue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
