# Generated by Django 5.2.10 on 2026-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='title',
        ),
        migrations.AddField(
            model_name='issue',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
