# Generated by Django 5.2.10 on 2026-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_remove_issue_title_issue_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
