# Generated by Django 5.2.10 on 2026-02-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_issue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('MED', 'medium'), ('HIGH', 'high')], default='MED', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('IN_PROGR', 'in progress'), ('RESOLVED', 'resolved'), ('CLOSED', 'closed')], default='OPEN', max_length=15),
        ),
    ]
