# Generated by Django 5.2.10 on 2026-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_priority_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('IN_PROGRESS', 'in_progress'), ('RESOLVED', 'resolved'), ('CLOSED', 'closed')], default='OPEN', max_length=15),
        ),
    ]
