# Generated by Django 5.2.10 on 2026-02-16 10:49

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_alter_issue_issue_image_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/', validators=[common.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
