# Generated by Django 5.2.10 on 2026-03-22 19:32

import common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('cost_center', models.CharField(max_length=10)),
                ('cc_manager', models.CharField(max_length=30)),
                ('inventory_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('installed_on', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('facility_image', models.ImageField(blank=True, null=True, upload_to='facility_images/', validators=[common.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
