# Generated by Django 5.2.10 on 2026-02-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='cost_center',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='facility',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
