# Generated by Django 5.2.10 on 2026-02-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_facility_cost_center_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacilityType',
            new_name='Unit',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='facility_type',
            new_name='unit',
        ),
    ]
