# Generated by Django 5.2.10 on 2026-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_rename_facilitytype_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='image',
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_image',
            field=models.ImageField(blank=True, null=True, upload_to='facility_images/'),
        ),
    ]
