# Generated by Django 5.2.10 on 2026-04-03 12:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_facility_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
