# Generated by Django 5.2.10 on 2026-02-16 10:49

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_remove_facility_image_facility_facility_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_image',
            field=models.ImageField(blank=True, null=True, upload_to='facility_images/', validators=[common.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
