# Generated by Django 5.2.10 on 2026-04-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internal_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('m', 'm'), ('m2', 'm2'), ('m3', 'm3'), ('pcs', 'pcs')], default='pcs', max_length=10),
        ),
    ]
