# Generated by Django 5.2.10 on 2026-04-03 08:16

import cloudinary.models
import common.validators
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, validators=[common.validators.validate_file_size_1mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='image'),
            preserve_default=False,
        ),
    ]
