# Generated by Django 5.2.10 on 2026-04-03 11:39

import cloudinary.models
import common.validators
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[common.validators.validate_file_size_1mb, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='image'),
        ),
    ]
