# Generated by Django 5.2.10 on 2026-02-17 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0007_alter_issue_issue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField()),
                ('started_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
                ('performer', models.CharField(choices=[('INTERNAL_SERVICE', 'internal service'), ('EXTERNAL+SERVICE', 'external service'), ('EXTERNAL_DELIVERER', 'external deliverer'), ('TENDER_PROCEDURE', 'tender procedure')], default='EXTERNAL+SERVICE', max_length=40)),
                ('performer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_request', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='issues.issue')),
            ],
            options={
                'ordering': ['-started_on'],
            },
        ),
    ]
