# Generated by Django 5.2.10 on 2026-03-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceaction',
            name='requires_parts',
            field=models.CharField(choices=[('NO_NEED', 'no need'), ('FROM_WAREHOUSE', 'from warehouse'), ('IN_STOCK', 'in stock'), ('DELIVERY_WAITING', 'delivery waiting'), ('TENDER_PROCEDURE', 'tender procedure')], default='NO_NEED', max_length=30),
        ),
    ]
