# Generated by Django 5.2.10 on 2026-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceaction',
            name='performer',
            field=models.CharField(choices=[('INTERNAL_SERVICE', 'internal service'), ('EXTERNAL_SERVICE', 'external service'), ('EXTERNAL_DELIVERER', 'external deliverer'), ('TENDER_PROCEDURE', 'tender procedure')], default='INTERNAL_SERVICE', max_length=40),
        ),
    ]
