# Generated by Django 5.2.10 on 2026-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenanceaction_requires_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceaction',
            name='performer',
            field=models.CharField(choices=[('INTERNAL_SERVICE', 'internal service'), ('EXTERNAL_SERVICE', 'external service'), ('EXTERNAL_SUPPLIER', 'external supplier'), ('TENDER_PROCEDURE', 'tender procedure')], default='INTERNAL_SERVICE', max_length=40),
        ),
    ]
