# Generated by Django 5.2.10 on 2026-04-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenanceaction_performer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceaction',
            name='performer',
            field=models.CharField(choices=[('INTERNAL_SERVICE', 'Internal service'), ('EXTERNAL_SERVICE', 'External service'), ('EXTERNAL_SUPPLIER', 'External supplier'), ('TENDER_PROCEDURE', 'Tender procedure')], default='INTERNAL_SERVICE', max_length=40),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='requires_parts',
            field=models.CharField(choices=[('NO_NEED', 'No need'), ('FROM_WAREHOUSE', 'From warehouse'), ('DELIVERY_WAITING', 'Delivery waiting'), ('TENDER_PROCEDURE', 'Tender procedure')], default='NO_NEED', max_length=30),
        ),
    ]
